;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        basic-electric-colon
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        cljr-slash
        comment-dwim
        counsel-M-x
        counsel-yank-pop
        haml-electric-backspace
        indent-for-tab-command
        kill-region
        kmacro-call-macro
        mc/reverse-region
        org-metaleft
        org-metaright
        org-self-insert-command
        org-shiftright
        platformio-build
        sp-backward-sexp
        sp-backward-transpose-sexp
        sp-backward-up-sexp
        sp-convolute-sexp
        sp-down-sexp
        sp-forward-barf-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-forward-transpose-sexp
        sp-kill-sexp
        sp-raise-sexp
        sp-unwrap-sexp
        sp-wrap-round
        web-mode-element-content-select
        web-mode-element-rename
        web-mode-element-wrap
        ))

(setq mc/cmds-to-run-once
      '(
        cider-eval-dwim
        mouse-drag-vertical-line
        mouse-set-region
        platformio-build
        ))
